# Generated by Django 5.1.2 on 2024-11-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'Новая'), ('accepted', 'Принято в работу'), ('completed', 'Выполнено')], default='new', help_text='Выберите категорию', max_length=16),
        ),
    ]
