# Generated by Django 5.1.2 on 2024-11-01 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_claim_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='category',
        ),
        migrations.AddField(
            model_name='claim',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Выберите категорию', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
    ]
