# Generated by Django 5.1.2 on 2024-11-01 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_claim_category_claim_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='category',
            field=models.ForeignKey(default=1, help_text='Выберите категорию', on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
    ]
