# Generated by Django 5.1.2 on 2024-11-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_claim_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='comment',
            field=models.TextField(blank=True, help_text="Введите комментарий при смене статуса на 'Принято в работу'", null=True),
        ),
    ]
