# Generated by Django 5.1.2 on 2024-11-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_claim_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='admin_photo',
            field=models.ImageField(blank=True, null=True, upload_to='admin_photos/'),
        ),
    ]
